# Day 50/60 Sickit-learn day 4

In [1]:
# Handling missing data: simple imputer in python

In [2]:
import pandas as pd
import numpy as np

In [3]:
miles = pd.DataFrame({"farthest_run_mi": [40,60,np.nan,100,26,13,31,50]})

In [4]:
miles

farthest_run_mi
0             40.0
1             60.0
2              NaN
3            100.0
4             26.0
5             13.0
6             31.0
7             50.0

In [5]:
miles.isna().sum()

farthest_run_mi    1
dtype: int64

In [7]:
#Importing SimpleImputer from impute
from sklearn.impute import SimpleImputer

In [14]:
imp_mean = SimpleImputer(strategy="mean")

In [15]:
# Let's fit this 
imp_mean.fit_transform(miles)

array([[ 40.        ],
       [ 60.        ],
       [ 45.71428571],
       [100.        ],
       [ 26.        ],
       [ 13.        ],
       [ 31.        ],
       [ 50.        ]])

In [16]:
imp_median = SimpleImputer(strategy = "median")

In [17]:
imp_median.fit_transform(miles)

array([[ 40.],
       [ 60.],
       [ 40.],
       [100.],
       [ 26.],
       [ 13.],
       [ 31.],
       [ 50.]])

In [21]:
imp_mfreq = SimpleImputer(strategy = "most_frequent")

In [22]:
imp_mfreq.fit_transform(miles)

array([[ 40.],
       [ 60.],
       [ 13.],
       [100.],
       [ 26.],
       [ 13.],
       [ 31.],
       [ 50.]])

In [28]:
imp_const = SimpleImputer(strategy = "constant",fill_value = 13)

In [29]:
imp_const.fit_transform(miles)

array([[ 40.],
       [ 60.],
       [ 13.],
       [100.],
       [ 26.],
       [ 13.],
       [ 31.],
       [ 50.]])

In [31]:
names = pd.DataFrame({"Names":["lawang","lakpa","tsering",np.nan,"lhamo"]})

In [32]:
names

Names
0   lawang
1    lakpa
2  tsering
3      NaN
4    lhamo

In [34]:
fill_name= SimpleImputer(strategy = "constant", fill_value="lhasang")

In [35]:
fill_name.fit_transform(names)

array([['lawang'],
       ['lakpa'],
       ['tsering'],
       ['lhasang'],
       ['lhamo']], dtype=object)

In [36]:
imp_mean_i = SimpleImputer(strategy = "mean", add_indicator = True)

In [37]:
imp_mean_i.fit_transform(miles)

array([[ 40.        ,   0.        ],
       [ 60.        ,   0.        ],
       [ 45.71428571,   1.        ],
       [100.        ,   0.        ],
       [ 26.        ,   0.        ],
       [ 13.        ,   0.        ],
       [ 31.        ,   0.        ],
       [ 50.        ,   0.        ]])

In [42]:
a = pd.DataFrame({"Names":["lawang","lakpa","tsering",np.nan,"lhamo"],"farthest_run_mi": [40,60,100,np.nan,26]})

In [43]:
## Lets import make_column_transfomer froom compose
from sklearn.compose import make_column_transformer

In [45]:
a

Names  farthest_run_mi
0   lawang             40.0
1    lakpa             60.0
2  tsering            100.0
3      NaN              NaN
4    lhamo             26.0

In [50]:
ct = make_column_transformer((fill_name,['Names']),
(imp_mean,['farthest_run_mi']),
remainder="drop"
                             )

In [51]:
ct.set_output(transform = "pandas")

ColumnTransformer(transformers=[('simpleimputer-1',
                                 SimpleImputer(fill_value='lhasang',
                                               strategy='constant'),
                                 ['Names']),
                                ('simpleimputer-2', SimpleImputer(),
                                 ['farthest_run_mi'])])

In [54]:
new = ct.fit_transform(a)

In [55]:
new

simpleimputer-1__Names  simpleimputer-2__farthest_run_mi
0                 lawang                              40.0
1                  lakpa                              60.0
2                tsering                             100.0
3                lhasang                              56.5
4                  lhamo                              26.0